language: haskell
ghc: 7.8

install:
  - cabal install --only-dependencies --enable-tests
  - cabal install QuickCheck hspec

script:
  - cabal configure --enable-tests && cabal build
  - cabal test --show-details=always

branches:
  only:
    - master
